---
- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: rpi
    - role: k3s/install

- hosts: masters
  become: yes
  roles:
    - role: k3s/master
    
# - hosts: workers
#   become: yes
#   roles:
#     - role: k3s/worker
    