---

  - name: Enable cgroup in /boot/firmware/cmdline.txt
    lineinfile:
      path: /boot/firmware/cmdline.txt
      backrefs: yes
      regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
      line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      state: present
    register: cgroup

  - name: Reboot after changing cmdline.txt settings
    when: cgroup is changed
    ansible.builtin.reboot:

  - name: Wait for reboot
    wait_for_connection:
      sleep: 5
      delay: 5
      timeout: 150
    when: cgroup is changed
        
  - name: check devices came back successfully
    ansible.builtin.ping:
    when: cgroup is changed